name: Lint

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
          tools: composer:v2

      - name: Install PHP dependencies
        run: composer install

      - name: Run PHP-CS-Fixer
        run: composer php-cs-fixer
        continue-on-error: true

      - name: Don't Commit composer.json change
        run: git checkout -- composer.json

      - name: Commit any changes back to the repo
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "[GitHub Actions Bot: Generate Calendars]"
          git push
