name: Generate Calendars

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Generate Calendars
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
          tools: composer:v2

      - name: Install PHP dependencies
        run: composer install

      - name: Run iCal's build
        run: bin/gocal gen
        continue-on-error: false

      - name: Don't Commit composer.json change
        run: git checkout -- composer.json

      - name: Commit any changes back to the repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[GitHub Actions Bot: Publish iCal's Update]"
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
