name: Automated Release

on:
  workflow_run:
    workflows: ['Deploy Site']
    branches: [main]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Automated Release
    runs-on: ubuntu-latest
    timeout-minutes: 2
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Determine next semver patch version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Create a new patch release with the new calendar fragment
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.version.outputs.v-version }}
          tag_name: ${{ steps.version.outputs.v-version }}
          files: dist/*
          fail_on_unmatched_files: true
          body: '🕒 This release was [automatically generated and released](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) at ${{ steps.date.outputs.date }}.'
