name: Automated Release

on:
  workflow_run:
    workflows: ['Deploy Site']
    branches: [main]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Automated Release
    runs-on: ubuntu-latest
    timeout-minutes: 2
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Determine next semver patch version
        uses: reecetech/version-increment@28d33de033e97a304f77238d6a5db26039ca15d6 # 2026.8.4
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Create a new patch release with the new calendar fragment
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          name: ${{ steps.version.outputs.v-version }}
          tag_name: ${{ steps.version.outputs.v-version }}
          files: dist/*
          fail_on_unmatched_files: true
          body: '🕒 This release was [automatically generated and released](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) at ${{ steps.date.outputs.date }}.'
