name: Generate iCal file

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Generate iCal file
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none
          tools: composer:v2

      - name: Install PHP dependencies
        run: composer install

      - name: Run iCal build
        run: bin/gocal gen
        continue-on-error: false

      - name: Don't Commit composer.json change
        run: git checkout -- composer.json

      - name: Commit any changes back to the repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[GitHub Actions Bot: Publish iCal Update]"
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Determine next semver patch version
        uses: Benbentwo/increment-semver@master
        id: version
        with:
          version-level: '-p'

      - name: Create a new patch release with the new calendar fragment
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
          files: dist/gocal.ics
          fail_on_unmatched_files: true
          body: "Automated calendar release at ${{ steps.date.outputs.date }} for version ${{ steps.version.outputs.version }}."
